pos.words <- read.csv("pos.csv")
neg.words<- read.csv("neg.csv")
pos.words <- scan("pos.csv",what='character')
neg.words <- scan("neg.csv",what='character')
score.sentiment = function(sentences, pos.words, neg.words, .progress='none')
{
  require(plyr)
  require(stringr)
  scores = laply(sentences, function(sentence, pos.words, neg.words) {
    sentence = gsub('[[:punct:]]', '', sentence)
    sentence = gsub('[[:cntrl:]]', '', sentence)
    sentence = gsub('\\d+', '', sentence)
    word.list = str_split(sentence, '\\s+')
    words = unlist(word.list)
    pos.matches = match(words, pos.words)
    neg.matches = match(words, neg.words)
    pos.matches = !is.na(pos.matches)
    neg.matches = !is.na(neg.matches)
    score = sum(pos.matches) - sum(neg.matches)
    return(score)
  }, pos.words, neg.words, .progress=.progress )
  scores.df = data.frame(score=scores, text=sentences)
  return(scores.df)
}
tweets.text=laply(terror,function(t)t$getText())
a<-terror_finalCorpus$content
analysis = score.sentiment(a, pos.words, neg.words)
summary(analysis$score)
table(analysis$score)
hist(analysis$score)
count(analysis$score)
write.csv(analysis, "myResults.csv")
